### ISSUE TITLE
Chef cookbook Error occurred 'cannot load such file 

### ISSUE THREAD

**Issue by Ally0620** [chef-cookbooks/database#180]
i have created a default.rb as below and got return cannot load such file -- OpEN
how can i solve this?

root@switch:/var/chef/cache/cookbooks/apt/recipes# chef-client
Starting Chef Client, version 11.4.0
resolving cookbooks for run list: ["apt"]
Synchronizing Cookbooks:
  - apt
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/apt/recipes/default.rb
================================================================================

LoadError
---------
cannot load such file -- OpEN

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/apt/recipes/default.rb:14:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/apt/recipes/default.rb:

  7:  # All rights reserved - Do Not Redistribute
  8:  #
  9:
 10:  #execute "apt-get update" do
 11:  #  command "apt-get update"
 12:  #end
 13:
 14>> require "OpEN"
 15:  require "OpENUtil"
 16:
 17:  open = OpENUtil.new()
 18:    conn_ret = open.connect("boa-vlan")
 19:    exists = false
 20:    if conn_ret == OpEN::OPEN_E_NONE
 21:      client = open.client
 22:      ret = OpEN::openapiVlanCreatedCheck(client,1)
 23:      if ret == OpEN::OPEN_E_NONE

[2015-10-12T07:11:15+00:00] ERROR: Running exception handlers
[2015-10-12T07:11:15+00:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
[2015-10-12T07:11:15+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated
[2015-10-12T07:11:15+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-10-12T07:11:15+00:00] FATAL: LoadError: cannot load such file -- OpEN

**Comment by iennae** [comment]
Hi @Ally0620,

This is the cookbook database issues on github, so this isn't the right place for this specific question. A better place is the mailing list https://www.chef.io/community/. Also I'd encourage you to take a look at the free resources and tutorials we have available on https://learn.chef.io/ to learn more about using chef.

To give you a little guidance here on your problem that you're seeing, the stack track is actually telling you what's wrong. The line

 [2015-10-12T07:11:15+00:00] FATAL: LoadError: cannot load such file -- OpEN

is telling you that it can't find the file OpEN.

Earlier in the stack track it's telling you

14>> require "OpEN"

and that >> is pointing to the error. So your recipe includes a line that says require "OpEN" that doesn't exist.

I'm not sure if you are trying to use the community cookbook apt and you've updated it or if you've created a brand new cookbook.

I also noticed you had the open issue:
https://bugs.ruby-lang.org/issues/11574

You probably don't want to update the apt recipe. 

You want to have a separate cookbook. If you have chef-dk installed, you will get the chef utility. The chef utility comes with a generator that will allow you to create a cookbook. chef generate cookbook NAMEOFCOOKBOOK.

Depending on what you want to do, this vlan connection looks like a separate library that you want to have available in the cookbook, and not within the recipe itself. Before using the library you need to make sure that any dependencies (like OpEN) are available. 

Nodes managed by chef-client could potentially have 2 instances of ruby (depending on the node type). One is the standard, system-wide instance of Ruby and the other is a dedicated instance that is available only to the chef-client. Use the chef_gem resource to install gems into the instance of Ruby that is dedicated to the chef-client. Use the gem_package resource to install all other gems (i.e. install gems system-wide). 

The reason OpEN is available to you from the command line and not from chef-client is because in the context of the chef-client run, it doesn't know about OpEN.

I hope this is helpful. Please do check out the mailing lists to have further help.

Thanks.
