### ISSUE TITLE
Resource PostgresqlDatabaseUser no longer has password method

### ISSUE THREAD

**Issue by ianbamforth** [chef-cookbooks/database#202]
Used to be inherited from resource DatabaseUser, but #193 removed that.  5.1.0 release is broken as a result, at least as far as I can tell - my build process bombed out because of it:

    NoMethodError
    -------------
    undefined method `password' for Chef::Resource::PostgresqlDatabaseUser

**Comment by marcospy** [comment]
I have the same problem!

**Comment by bdrust** [comment]
same issue here

**Comment by jharveysmith** [comment]
I ran into this also.

**Comment by donaldguy** [comment]
New with the `5.1.0` release, adding a Berksfile lock to `5.0.1` returns to working

Please fix.

**Comment by davedcusack** [comment]
Came across this myself, as a work around for the mean time you can change the dependency to depends 'database', '~> 5.0.0'

**Comment by mvdkleijn** [comment]
This problem was introduced in 5.1.0... upon looking at the Travis CI build, I see the automated tests failed on exactly this issue. Can I be so bold as to ask why this release happened despite non-trivial tests failing? :smile: (failure due to a style issue or something is fine, but broken functionality...)

**Comment by tas50** [comment]
Fix is on it's way.  Locking the thread for now.  +1s to the issue aren't helping.

**Comment by tas50** [comment]
Give it a try with 5.1.1
