### ISSUE TITLE
Providers/examples section in the README seems to be duplicated

### ISSUE THREAD

**Issue by williewheeler** [chef-cookbooks/database#98]
Looks like the Providers/Examples sections are duplicated under the database_user section.

**Comment by iennae** [comment]
Can you check to see if the updated README resolves the issues you were seeing? I understand it's been a while since you reported this so you may no longer care about this particular issue. I'm going to close this, but please do reopen if it's still a problem that you're concerned with.

Thanks for giving us feedback about our docs!
